// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqXSy1-TdkfYe1rGEnDjuFnIS5ayKhJDs',
    appId: '1:572157186402:android:fb3461668e9e0e5e8b5c3b',
    messagingSenderId: '572157186402',
    projectId: 'daftaruser-projectt',
    storageBucket: 'daftaruser-projectt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2T1G97JRXKQ4lXw-8y8YaJuHdR4-Cdrk',
    appId: '1:572157186402:ios:4c094393c050eabd8b5c3b',
    messagingSenderId: '572157186402',
    projectId: 'daftaruser-projectt',
    storageBucket: 'daftaruser-projectt.firebasestorage.app',
    iosBundleId: 'com.example.api',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUhr_MDIM_j0LPkSn69S5Bioa_r7jnhEw',
    appId: '1:572157186402:web:b12167c68791fe5e8b5c3b',
    messagingSenderId: '572157186402',
    projectId: 'daftaruser-projectt',
    authDomain: 'daftaruser-projectt.firebaseapp.com',
    storageBucket: 'daftaruser-projectt.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2T1G97JRXKQ4lXw-8y8YaJuHdR4-Cdrk',
    appId: '1:572157186402:ios:4c094393c050eabd8b5c3b',
    messagingSenderId: '572157186402',
    projectId: 'daftaruser-projectt',
    storageBucket: 'daftaruser-projectt.firebasestorage.app',
    iosBundleId: 'com.example.api',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUhr_MDIM_j0LPkSn69S5Bioa_r7jnhEw',
    appId: '1:572157186402:web:bafea94e83c826218b5c3b',
    messagingSenderId: '572157186402',
    projectId: 'daftaruser-projectt',
    authDomain: 'daftaruser-projectt.firebaseapp.com',
    storageBucket: 'daftaruser-projectt.firebasestorage.app',
  );

}